### ISSUE TITLE
PR: torch 1.4+ compatibility

### ISSUE THREAD

**Issue by Kostis-S-Z** [mattriemer/MER#1]
Firstly, thank you for open sourcing a well structured and easy to follow repo.

I have upgraded the code for Python 3.6+ and the latest torch (1.4.0) & torchvision (0.5.0) and have run some small tests to make sure everything still works as it should. Could I open a pull request so you can review the changes?

**Comment by mattriemer** [comment]
Thank you so much for doing this! I have reviewed your very helpful changes and accepted the pull request. We have run some small tests as well and it appears that the new backward compatibility issues have been addressed. Your efforts are very much appreciated and should make this repository more useful moving forward as others try to integrate with newer versions of PyTorch and Python.

**Comment by Kostis-S-Z** [comment]
Glad to help and contribute! :)
