### ISSUE TITLE
The eval of MER

### ISSUE THREAD

**Issue by guozhiyao** [mattriemer/MER#3]
When we adapt the meta-model to a new task, we need to train the meta-model on the training set of the new task. But the eval_tasks function in MER seems to eval on the test  set of new tasks directly. Is that a problem? Does MER still belongs to meta-learning approch?

**Comment by mattriemer** [comment]
Hi thank you for your question! Our paper is about a method for applying meta-learning in continual learning settings. As such, our evaluation setting is modeled after prior work on continual learning. Our eval_tasks code comes directly from the GEM project https://github.com/facebookresearch/GradientEpisodicMemory, which was the main point of comparison in our paper. Maybe your confusion is related to meta-training and meta-testing? We do not have any notion of meta-training and meta-testing in or work. In fact, this can be seen as one of the main innovations of our paper. MER applies meta-learning in a generic continual learning setting without the need to break learning up into multiple separate phases. The main.py file is not specific to the MER approach and is almost exactly taken from the GEM repository. The eval_tasks function is simply used for reporting results over time as training progresses -- not for actually training the model. Most of the code provided follows the protocol from the GEM paper with our main contribution being in the meralg*.py files in the model directory. I hope this helps! However, I am not sure if I totally understood your concern, so feel free to clarify if this response doesn't make sense.

**Comment by guozhiyao** [comment]
Thanks for your reply. In my opinion, your work is extending from Reptile and GEM. And the Reptile does not need to seperate the train-set of train-task into support-set and query-set, which trains on the whole train-set of train-task directly. But in the eval of Reptile, it still need to train on the train-set of test-task, and then test on the test-set of test-task, which adapt the meta-model on the test-task.
Is that your work mainly uses Reptile's framework and focus on  solving the lifelong learning problem without considering the capacity of meta learning to adapt to new task?

**Comment by guozhiyao** [comment]
Thanks for your reply. In my opinion, your work is extending from Reptile and GEM. And the Reptile does not need to seperate the train-set of train-task into support-set and query-set, which trains on the whole train-set of train-task directly. But in the eval of Reptile, it still need to train on the train-set of test-task, and then test on the test-set of test-task, which adapt the meta-model on the test-task.
Is that your work mainly uses Reptile's framework and focus on  solving the lifelong learning problem without considering the capacity of meta learning to adapt to new task?

**Comment by mattriemer** [comment]
Yes. In this paper we were focused on evaluating our approach in a lifelong continual learning setting. The model must adapt to new tasks when they are presented without forgetting old tasks. The improved adaption can be seen based on improvements on metrics like forward transfer and backward transfer as well as accuracy on tasks directly after learning and retained accuracy after learning all tasks. We did not, however, consider a meta-testing or few-shot learning based evaluation setting. This would be a lot closer to the original Reptile paper, which was not our goal here.
